### PR TITLE
change delete_mails_after default to 20

### LINKED ISSUE #298: delete_mails_after = 40 is too high
@hagenest just ran into the 100MB limit.

Also, GDPR has a frist of 1 month, which is why it makes sense to keep mails less than that if we want to have a minimalist privacy policy. Maybe 20 days?

Should this be the new default or should we just change it for nine.testrun.org?

### PR DESCRIPTION
**Pull request by hagenest**
closes #298

### CODE REVIEW

**Comment by hagenest** [comment]
yeah, turns out the test values need to changed as well, lol

**Comment by missytake** [comment]
oops, I meant to rebase. Let me fix this

**Review by missytake — APPROVED** [review]
Looks good :) only a changelog item is missing. I think it makes sense to notify admins of existing instances that we changed the default, but it's on them if they want to follow our new recommendation.

**Comment by hagenest** [comment]
true, don't know, why I forgot. done

**Pull request merged**
