### PR TITLE
Hardening nginx.j2

### PR DESCRIPTION
**Pull request by nudeldudel**
The same as in Issue #77 , but for nginx now.

### CODE REVIEW

**Comment by hpk42** [comment]
Not sure there is much point in hardening nginx -- it's not required for chatmail usages from delta chat, and the distributions / debian defaults should be fine enough.  Thanks for the suggestion, though!

**Comment by nudeldudel** [comment]
I don't agree completly. The complete server will be attacked, as it is a concurence to "the others". 

On the other site, there is no reason against this change. Or will user be blocked, becuase only can use weak ciphers....

If chatmail is audited by "experts", this will be an other point of critic.

**Comment by hpk42** [comment]
so i guess it's ok to change the PR to only require TLS v1.2 and not change ciphers?  would be fine with that.

**Comment by n3ph** [comment]
In the end, nginx is only used for the "welcome page" to register a new account. 
Since the registration process is usually done through the application (handheld, desktop), TLS version constraints are (probably/hopefully?) set by client implementation.

To narrow down used TLS versions (keep downgrade attacks in mind‼️), this change absolutely makes sense and I explicitly challenge closing this PR.

Best regards ✌🏼

**Pull request closed without merging**
