### PR TITLE
Guide on how to migrate chatmail to a new host

### PR DESCRIPTION
**Pull request by missytake**
This guide doesn't require knowing about firewalls, but utilizes the `cmdeploy run --disable-mail` command from #428 and the `cmdeploy run --ssh-host` command from #439. Should be merged after those.

supercedes #417

Tested by migrating c2 back and forth, especially the second time worked like a charm :)

### CODE REVIEW

**Comment by missytake** [comment]
I wonder whether we should also preserve the DKIM key, as it might lead to rejected messages if multiple keys are around for the same dkim selector.

**Review by hpk42 — COMMENTED** [review]
To be honest, it all looks workable but also rather error-prone/tedious, especially the constant overwriting of host identity keys. 
I think we need a "cmdeploy --ssh-host=sshname" option because then one can just add "old" and "new" to `/etc/hosts` and do "cmdeploy --ssh-host=old run" etc, and skip all the hostkey-overwriting. It should also help with the NAT-issue and should not be hard to do.

**Comment by missytake** [comment]
> > I wonder whether we should also preserve the DKIM key, as it might lead to rejected messages if multiple keys are around for the same dkim selector.
> 
> I think we should generate a new DKIM selector for each deployment. Using current date like 20241017 for the selector name. Ideally DKIM selector to key mapping should be possible to cache indefinitely, so reusing DKIM selectors is not a good idea.

Do you consider #195 a blocker for merging this?

**Comment by missytake** [comment]
> To be honest, it all looks workable but also rather error-prone/tedious, especially the constant overwriting of host identity keys. I think we need a "cmdeploy --ssh-host=sshname" option because then one can just add "old" and "new" to `/etc/hosts` and do "cmdeploy --ssh-host=old run" etc, and skip all the hostkey-overwriting. It should also help with the NAT-issue and should not be hard to do.

With https://github.com/deltachat/chatmail/pull/429/commits/c9b574b87d7ab3c0b05a913eb27d8b7317ceb1c2 we're down from 16 to 9 steps :)))

**Review by hpk42 — APPROVED** [review]
overall looks great, some minor comments only. 
Haven't run it myself though. 
Changelog entry is missing.

**Pull request merged**
